### ISSUE TITLE
Erro ao executar scripts do gulp

### ISSUE THREAD

**Issue by sfelix-martins** [Plataformas-Cidadania/mapa-osc-client#12]
E aí galera, blz?

Está ocorrendo um erro ao executar os scripts do gulp para buildar o JS.
```
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/home/samuelmartins/Projects/open-source/ipea/plataformas-cidadania/mapa-osc-client/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/samuelmartins/Projects/open-source/ipea/plataformas-cidadania/mapa-osc-client/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/samuelmartins/Projects/open-source/ipea/plataformas-cidadania/mapa-osc-client/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37
```

## Ambiente

- Branch: 2.8.0
- Npm 6.10.2
- Node 12.8.0

## Como simular

- Clone o projeto
- Faça checkout na branch `2.8.0`: `git checkout 2.8.0` 
- Instale as dependencias do npm: `npm install`
- Execute algum dos scripts do gulp. Ex.: `gulp scripts4`

**Comment by EricFerreiraS** [comment]
https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node

**Comment by sfelix-martins** [comment]
Eu fiz o downgrade do meu node js para `v10.16.2` e funcionou. Vlw @EricFerreiraS.

## Passos executados

Fix o downgrade do node:

```sh
sudo npm install -g n
sudo n 10.16.2
```

E executei o script de minificar na raiz do projeto:

```sh
./node_modules/gulp/bin/gulp.js min
```
